### ISSUE TITLE
Nrf52 NFC Interrupt lost

### ISSUE THREAD

**Issue by Aleksa21** [LumenRadio/miramesh-zephyr#1]
I've integrated Miramesh into my NCS 2.5.0-based project, and I have issues with NFC.

I use a nordic library for NFC t4t on nrf52.

Before integrating Miramesh into the project, upon each NFC activity, I would get a callback called, which was registered like this:
`nfc_t4t_setup(nfc_callback, NULL);`

After integrating Miramesh, I can read/write to my tag, but the above callback is never called. 

NFC provides proper value upon a read request after the initialization. But on each write request, it just forwards the data that was received to the upcoming read requests. So basically after I write once to my NFC tag, if I do a read afterwards, I'll get the same value that I just wrote.

I've played around a bit with miramesh integration, and after debugging the code, I am pretty sure it's related to this IRQ handler:
`
ISR_DIRECT_DECLARE(swi1_irq_handler)
{
    miramesh_swi1_irq_handler();
    return 0;
}
`

But I don't know how to adjust it in order to have the NFC work as it used to do.

I've also tried to make a new NFC module based on Mira-NFC, but I failed to do so because the integration library (nrf52840sdc-net/libmira.a) has no functions for Mira-NFC so it seems impossible to do so.

**Comment by bofh69** [comment]
Hi!

Please open a support ticket at https://support.lumenradio.com/ and we'll take a look at it.

BR,
Sebastian

**Comment by Aleksa21** [comment]
Hi Sebastian!

I have opened a ticket, but it mostly just provides a link to this issue.
Ticket id: 4864

Regards,
Aleksa
